version: '3.1'
services:
  jenkins:
    container_name: jenkins
    restart: always
    image: avillach-lab-dev-jenkins
    environment:
      - stack_s3_bucket
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
        - '80:8080'
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /var/log/jenkins-docker-logs/:/var/log
        - /var/jenkins_home/jobs/:/var/jenkins_home/jobs/
        - /var/jenkins_home/workspace/:/var/jenkins_home/workspace/

